<?php include __DIR__ . "/../public/header.phtml"; ?>
<script src="/js/admin.js"></script>
<a class="btn btn-success" href="/admin/node/add"> 添加节点</a>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <!-- # 	节点中文名 	节点英文名 	节点状态 	创建时间 	修改时间 	操作-->
            <th>节点中文名</th>
            <th>节点英文名</th>
            <th>节点状态</th>
            <th>创建时间</th>
            <th>修改时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($node as $k1 => $v1) { ?>
            <tr>
                <th><?php echo $v1['node_name'] ?></th>
                <th><?php echo $v1['node_ename'] ?></th>
                <th><?php echo ($v1['status'] == NodeModel::STATUS_ENABLE) ? '启用' : '禁用'; ?></th>
                <th><?php echo $v1['create_time'] ?></th>
                <th><?php echo $v1['update_time'] ?></th>
                <th>
                    <a href="/admin/node/add/id/<?php echo $v1['id']; ?>">修改</a>
                    <a onclick="ajax_sub('/admin/node/able',{'id':<?php echo $v1['id']; ?>,
                        'able':<?php echo ($v1['status'] == NodeModel::STATUS_ENABLE) ?
                        NodeModel::STATUS_DISABLE : NodeModel::STATUS_ENABLE; ?>
                        })">
                        <?php echo ($v1['status'] == NodeModel::STATUS_ENABLE) ? '禁用' : '启用'; ?>
                    </a>
                </th>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<?php include __DIR__ . "/../public/footer.phtml"; ?>

