

</div>
</div>
<!--End Content-->
</div>
</div>
<!--End Container-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="http://code.jquery.com/jquery.js"></script>-->
<script src="/css/plugins/jquery/jquery.min.js"></script>
<script src="/css/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/css/plugins/bootstrap/bootstrap.min.js"></script>
<script src="/css/plugins/justified-gallery/jquery.justifiedGallery.min.js"></script>
<script src="/css/plugins/tinymce/tinymce.min.js"></script>
<script src="/css/plugins/tinymce/jquery.tinymce.min.js"></script>
<!-- All functions for this theme + document.ready processing -->
<script src="/js/devoops.js"></script>
</body>
</html>